### ISSUE TITLE
no admin page

### ISSUE THREAD

**Issue by isundaniyal** [justdjango/django-react-boilerplate#10]
cannot display admin page (/admin/

**Comment by wefhi** [comment]
Maybe you are using localhost:8000

Try 127.0.0.1:8000 instead since it's allowed in ALLOWED_HOSTS in settings.py

**Comment by Ucheogbu** [comment]
Comment out the last URL pattern at home.URLs as it is meant for production, it matches everything so other patterns won't be seen. this is a quick fix, for a better solution you can check if settings is in production or dev mode and add the pattern when appropriate.

**Comment by mattfreire** [comment]
Seems resolved. Thanks @Ucheogbu
