### ISSUE TITLE
I  dont have a Build Directory

### ISSUE THREAD

**Issue by BwanaQ** [justdjango/django-react-boilerplate#11]
Hi I'm quite new at this but managed to clone and start the project but i get a TemplateDoesNotExist error since the app does not have a build directory

**Comment by wefhi** [comment]
You are getting TemplateDoesNotExist because you should not use your backend on port 8000


Try using localhost:3000 React sends data to this port

**Comment by reypryma** [comment]
wefhi but in the lecture you can see the backend do have view
