### ISSUE TITLE
Error after npm start

### ISSUE THREAD

**Issue by jersonjunior** [justdjango/django-react-boilerplate#2]
I get the following error after running the npm i and npm start commands:

> ./node_modules/semantic-ui-css/semantic.min.css (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-3-1!./node_modules/postcss-loader/src??postcss!./node_modules/semantic-ui-css/semantic.min.css)
> Error: Cannot find module '@csstools/normalize.css'

**Comment by devgreek** [comment]
delete the node modules folder and npm install again
