### ISSUE TITLE
favicon.ico is not getting added in the production build

### ISSUE THREAD

**Issue by aashayamballi** [justdjango/django-react-boilerplate#7]
When I run the production build using `npm run build ` and I run the Django test server, the favicon.ico is missing and in the console I get an error Manifest: Line: 1, column: 1, Syntax error.

**Comment by carlosalvarez91** [comment]
@aashayamballi when deploying the app to a server you will have to specify where favicon.ico is located. This is an example using nginx:

   location ~* favicon.ico {
      root /root/to/project/frontend/build;
   }
